  name: scp files
jobs: on push
build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 127.0.0.1
        username: root
        password: mypassword
        source: "/"
        target: "/var/www/html/mywebsite/"
