  name: scp files
   push:
   branches: [ main ]
jobs: on push
build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 13.233.58.152
        username: root
        password: passwd
        source: "/"
        target: "/var/www/html/"
