  name: scp files
   push:
   branches: [ master ]
jobs: on push
build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 13.233.58.152
        username: root
        password: mypassword
        source: "/"
        target: "/var/www/html/mywebsite/"
