name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps: 
    - 
      uses: actions/checkout@master
    - 
      name: "copy file via ssh password"
      uses: appleboy/scp-action@master
      with: 
        host: "13.233.58.152"
        password: passwd
        source: /
        target: /var/www/html/
        username: root
