name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps: 
    - 
      uses: actions/checkout@master
    - 
      name: "copy file via ssh password"
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}
        source: "."
        target: /var/www/html/
        
