name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps: 
    - 
      uses: actions/checkout@master
    - 
      name: " copy file via ssh key"
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets_HOST }}
        key: ${{ secrets_KEY }}
        username: ${{ secrets_USERNAME }}
        port: ${{ secrets_PORT }}
        password: ${{ secrets_PASSWORD }}
        source: "."
        target: /var/www/html/
        
